# Generated by Django 3.0.5 on 2020-04-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200426_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='description',
        ),
    ]
